### ISSUE TITLE
Cannot run main.py

### ISSUE THREAD

**Issue by cjy513203427** [M-3LAB/open-iad#3]
Hi. Which python version do you use?
I tried python 3.8, 3.9, 3.10 I got the following errors:
`(open-iad) jinyao@jinyao-System-Product-Name:~/projects/open-iad$ python3 main.py -v -m cfa -n net_cfa -d mvtec2d -tid 0 -vid 0 -g 1
Traceback (most recent call last):
  File "/home/jinyao/projects/open-iad/main.py", line 26, in <module>
    main(args)
  File "/home/jinyao/projects/open-iad/main.py", line 11, in main
    work.run_work_flow()
  File "/home/jinyao/projects/open-iad/paradigms/centralized/c2d.py", line 140, in run_work_flow
    self.load_config()
  File "/home/jinyao/projects/open-iad/paradigms/centralized/c2d.py", line 30, in load_config
    ip, root_path = assign_service(self.para_dict['server_moda'])
  File "/home/jinyao/projects/open-iad/configuration/device.py", line 15, in assign_service
    ip = get_ip_address(moda)
  File "/home/jinyao/projects/open-iad/configuration/device.py", line 9, in get_ip_address
    info = fcntl.ioctl(s.fileno(), 0x8915, struct.pack('256s', bytes(ifname[:15], 'utf-8')))
OSError: [Errno 19] No such device
`

**Comment by lgbLevi** [comment]
Perhaps you can change the last line in file:  /open-iad/configuration/2_train_base/centralized_learning.yaml
server_moda: lo
