### ISSUE TITLE
Don't find the path

### ISSUE THREAD

**Issue by kinghge** [M-3LAB/open-iad#4]
hello ,thanks author share the open-iad ,but I have some problems .
I don't find the path in which file ::: '/home/robot/data/mvtec2d/bottle/train'
this is some errors:
Traceback (most recent call last):
  File "/home/kinghge/Desktop/open-iad-main/open-iad-main/main.py", line 26, in <module>
    main(args)
  File "/home/kinghge/Desktop/open-iad-main/open-iad-main/main.py", line 11, in main
    work.run_work_flow()
  File "/home/kinghge/Desktop/open-iad-main/open-iad-main/paradigms/centralized/c2d.py", line 142, in run_work_flow
    self.load_data()
  File "/home/kinghge/Desktop/open-iad-main/open-iad-main/paradigms/centralized/c2d.py", line 66, in load_data
    dataloader = DataHolder(dataset_class, self.para_dict)
  File "/home/kinghge/Desktop/open-iad-main/open-iad-main/data_io/data_holder.py", line 17, in __init__
    self.train_dataset = dataset_class(data_path=self.config['data_path'],
  File "/home/kinghge/Desktop/open-iad-main/open-iad-main/dataset/mvtec2d.py", line 42, in __init__
    self.load_dataset()
  File "/home/kinghge/Desktop/open-iad-main/open-iad-main/dataset/mvtec2d.py", line 83, in load_dataset
    img_types = sorted(os.listdir(img_dir))
FileNotFoundError: [Errno 2] No such file or directory: '/home/robot/data/mvtec2d/bottle/train'

**Comment by AsadiAhmad** [comment]
maybe you are bypassing the ip with 127.0.0.1 (local ip address) then in configuration folder in registration.py file we have some config like this :
server_data = {'127.0.0.1': '/home/robot/data',
               '172.18.36.108': '/ssd2/m3lab/data/open-ad',
               '172.18.36.107': '/ssd-sata1/wjb/data/open-ad',
              }
then the root address of your project is going to /home/robot/data
if you bypass the ip address you can't download automatically form server and after changing the root of your project you need to download the dataset by yourself more clear code is in google colab version.
